name: UniversalMinecraftAPI
main: com.koenv.universalminecraftapi.spigot.SpigotUniversalMinecraftAPI
version: $version
commands:
   universalminecraftapi:
      description: The UniversalMinecraftAPI base command
      usage: /<command>
      aliases: [uma]